- type: job
  id: Mercenary
  name: job-name-mercenary
  description: job-description-mercenary
  playTimeTracker: JobMercenary
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000
  startingGear: MercenaryGear
  canBeAntag: true
  icon: "JobIconMercenary"
  supervisors: job-supervisors-captain
  setPreference: false
  access:
  - Maintenance
  - External
  - Mercenary

- type: startingGear
  id: MercenaryGear
  equipment:
    ears: ClothingHeadsetAltMercenary
